import type { AppToast, HistoryItem, Project, RequestError } from "../api/types";
import { useAppStore } from "./store";

export const useHistory = (): HistoryItem[] => useAppStore((state) => state.history);
export const useProjectId = (): string => useAppStore((state) => state.projectId);
export const useProjects = (): Project[] => useAppStore((state) => state.projects);
export const useBaselineCommitId = (): string | undefined => useAppStore((state) => state.activeBaselineCommitId);
export const useSelectedCommitId = (): string | undefined => useAppStore((state) => state.selectedCommitId);
export const useCompareResult = () => useAppStore((state) => state.latestCompareResult);
export const useEvalRun = () => useAppStore((state) => state.latestEvalRun);
export const useRequestStates = () => useAppStore((state) => state.requestStates);
export const useLastError = (): RequestError | undefined => useAppStore((state) => state.lastError);
export const useToasts = (): AppToast[] => useAppStore((state) => state.toasts);
export const usePromptModalOpen = (): boolean => useAppStore((state) => state.promptModalOpen);
export const usePromptModalAnchorCommitId = (): string | undefined => useAppStore((state) => state.promptModalAnchorCommitId);
export const useEvalModalOpen = (): boolean => useAppStore((state) => state.evalModalOpen);
export const useEvalModalAnchorCommitId = (): string | undefined => useAppStore((state) => state.evalModalAnchorCommitId);
export const useCompareModalOpen = (): boolean => useAppStore((state) => state.compareModalOpen);
export const useCommitInfoCommitId = (): string | undefined => useAppStore((state) => state.commitInfoCommitId);
export const useGraphFullscreenOpen = (): boolean => useAppStore((state) => state.graphFullscreenOpen);
export const useCompareSelectionMode = (): boolean => useAppStore((state) => state.compareSelectionMode);
export const useCompareSelectionCommitIds = (): string[] => useAppStore((state) => state.compareSelectionCommitIds);
export const useDeleteTargetCommitId = (): string | undefined => useAppStore((state) => state.deleteTargetCommitId);
